// Code generated by command: go run zip_asm.go -pkg zip -out ../zip/zip_amd64.s -stubs ../zip/zip_amd64.go. DO NOT EDIT.

package zip

// Sum uint64s using avx2 instructions, results stored in x
func sumUint64(x []uint64, y []uint64)
