// Code generated by command: go run zip_asm.go -pkg zip -out ../zip/zip_amd64.s -stubs ../zip/zip_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func sumUint64(x []uint64, y []uint64)
// Requires: AVX, AVX2
TEXT ·sumUint64(SB), NOSPLIT, $0-48
	MOVQ x_base+0(FP), CX
	MOVQ y_base+24(FP), BX
	MOVQ x_len+8(FP), AX
	MOVQ y_len+32(FP), SI
	MOVQ CX, DI
	MOVQ BX, R8
	MOVQ $0x0000000000000008, R9
	MULQ R9
	ADDQ AX, DI
	MOVQ SI, AX
	MULQ R9
	ADDQ AX, R8

avx2_loop:
	MOVQ    CX, AX
	MOVQ    BX, DX
	ADDQ    $0x80, AX
	ADDQ    $0x80, DX
	CMPQ    AX, DI
	JAE     x86_loop
	CMPQ    DX, R8
	JAE     x86_loop
	VMOVDQU (CX), Y0
	VMOVDQU (BX), Y1
	VMOVDQU 32(CX), Y2
	VMOVDQU 32(BX), Y3
	VMOVDQU 64(CX), Y4
	VMOVDQU 64(BX), Y5
	VMOVDQU 96(CX), Y6
	VMOVDQU 96(BX), Y7
	VPADDQ  Y0, Y1, Y0
	VPADDQ  Y2, Y3, Y2
	VPADDQ  Y4, Y5, Y4
	VPADDQ  Y6, Y7, Y6
	VMOVDQU Y0, (CX)
	VMOVDQU Y2, 32(CX)
	VMOVDQU Y4, 64(CX)
	VMOVDQU Y6, 96(CX)
	MOVQ    AX, CX
	MOVQ    DX, BX
	JMP     avx2_loop

x86_loop:
	CMPQ CX, DI
	JAE  return
	CMPQ BX, R8
	JAE  return
	MOVQ (CX), AX
	ADDQ (BX), AX
	MOVQ AX, (CX)
	ADDQ $0x08, CX
	ADDQ $0x08, BX
	JMP  x86_loop

return:
	RET
