// Code generated by command: go run despacer_asm.go -pkg despacer -out ../despacer/despacer_amd64.s -stubs ../despacer/despacer_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func Despace(data []byte)
// Requires: AVX, AVX2, SSE4.1
TEXT ·Despace(SB), NOSPLIT, $0-24
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	XORQ         DX, DX
	MOVB         $0x20, BL
	PINSRB       $0x00, BX, X0
	VPBROADCASTB X0, Y0
	MOVB         $0x0a, BL
	PINSRB       $0x00, BX, X1
	VPBROADCASTB X1, Y1
	MOVB         $0x0d, BL
	PINSRB       $0x00, BX, X2
	VPBROADCASTB X2, Y2

avx2_loop:
	// just created ahead
	MOVQ     $0x0000000000000020, BX
	ADDQ     BX, DX
	CMPQ     DX, CX
	JAE      x86_loop
	VLDDQU   (AX), Y3
	VPCMPEQB Y3, Y0, Y4
	VPCMPEQB Y3, Y1, Y5
	VPCMPEQB Y3, Y2, Y3
	VPOR     Y4, Y5, Y4
	VPOR     Y3, Y4, Y4
	VPOR     Y6, Y6, Y6
	VPTEST   Y4, Y4
	JNZ      remove_space
	JMP      avx2_loop

remove_space:
x86_loop:
	JAE return

return:
	RET
