// Code generated by command: go run despacer_asm.go -pkg despacer -out ../despacer/despacer_amd64.s -stubs ../despacer/despacer_amd64.go. DO NOT EDIT.

package despacer

// remove spaces (in-place) from string bytes (UTF-8 or ASCII)
func Despace(data []byte)
