// Code generated by command: go run bswapq_asm.go -pkg bswap -out ../bswap/bswapq_amd64.s -stubs ../bswap/bswapq_amd64.go. DO NOT EDIT.

package bswap

// bswapq performs an in-place byte swap on each qword of the input buffer.
func bswapq(b []byte)
