// Code generated by command: go run sums_asm.go -pkg slices -out ../slices/sums_amd64.s -stubs ../slices/sums_amd64.go. DO NOT EDIT.

package slices

// Sum uint32s using avx2 instructions, results stored in x
func sumUint32(x []uint32, y []uint32)

// Sum uint64s using avx2 instructions, results stored in x
func sumUint64(x []uint64, y []uint64)
