// Code generated by command: go run dedupe16_asm.go -pkg dedupe -out ../dedupe/dedupe16_amd64.s -stubs ../dedupe/dedupe16_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func dedupe16(b []byte) (pos int)
// Requires: SSE, SSE2, SSE4.1
TEXT ·dedupe16(SB), NOSPLIT, $0-32
	MOVQ   b_base+0(FP), AX
	MOVQ   b_len+8(FP), CX
	MOVQ   AX, DX
	ADDQ   CX, DX
	MOVUPS (AX), X0
	ADDQ   $0x10, AX
	MOVQ   AX, CX

loop:
	CMPQ     AX, DX
	JE       done
	MOVUPS   (AX), X1
	MOVUPS   X1, X2
	PCMPEQQ  X0, X2
	MOVMSKPD X2, BX
	CMPL     BX, $0x03
	JE       next
	MOVUPS   X1, (CX)
	ADDQ     $0x10, CX
	MOVUPS   X1, X0

next:
	ADDQ $0x10, AX
	JMP  loop

done:
	MOVQ b_base+0(FP), AX
	SUBQ AX, CX
	MOVQ CX, pos+24(FP)
	RET
