// Code generated by command: go run blend_asm.go -pkg mem -out ../mem/blend_amd64.s -stubs ../mem/blend_amd64.go. DO NOT EDIT.

package mem

// AVX optimized version for medium to large size inputs.
func Blend(dst []byte, src []byte) int
