// Code generated by command: go run contains_asm.go -pkg mem -out ../mem/contains_amd64.s -stubs ../mem/contains_amd64.go. DO NOT EDIT.

//go:build !purego

package mem

func ContainsByte(haystack []byte, needle byte) bool
