// Code generated by command: go run copy_asm.go -pkg mem -out ../mem/copy_amd64.s -stubs ../mem/copy_amd64.go. DO NOT EDIT.

//go:build !purego

package mem

// Copy copies src to dst, returning the number of bytes written.
func Copy(dst []byte, src []byte) int
