// Code generated by command: go run copy_asm.go -pkg mem -out ../mem/copy_amd64.s -stubs ../mem/copy_amd64.go. DO NOT EDIT.

package mem

// AVX optimized version for medium to large size inputs.
func Copy(dst []byte, src []byte) int
