// Code generated by command: go run count_pair_asm.go -pkg mem -out ../mem/count_pair_amd64.s -stubs ../mem/count_pair_amd64.go. DO NOT EDIT.

//go:build !purego

package mem

func countPair1(b []byte) int

func countPair2(b []byte) int

func countPair4(b []byte) int

func countPair8(b []byte) int

func countPair16(b []byte) int

func countPair32(b []byte) int
