// Code generated by command: go run index_pair_asm.go -pkg mem -out ../mem/index_pair_amd64.s -stubs ../mem/index_pair_amd64.go. DO NOT EDIT.

//go:build !purego

package mem

func indexPair1(b []byte) int

func indexPair2(b []byte) int

func indexPair4(b []byte) int

func indexPair8(b []byte) int

func indexPair16(b []byte) int

func indexPair32(b []byte) int
