// Code generated by command: go run index_pair_asm.go -pkg mem -out ../mem/index_pair_amd64.s -stubs ../mem/index_pair_amd64.go. DO NOT EDIT.

package mem

// indexPair1 is the x86 specialization of mem.IndexPair for items of size 1
func indexPair1(b []byte) int
