// Code generated by command: go run index_pair_asm.go -pkg mem -out ../mem/index_pair_amd64.s -stubs ../mem/index_pair_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func indexPair1(b []byte) int
// Requires: AVX, AVX2, BMI
TEXT ·indexPair1(SB), NOSPLIT, $0-32
	MOVQ b_base+0(FP), AX
	MOVQ b_len+8(FP), CX
	CMPQ CX, $0x01
	JBE  done
	MOVQ AX, DX
	MOVQ AX, BX
	ADDQ CX, BX
	SUBQ $0x01, BX
	CMPQ CX, $0x21
	JBE  generic
	BTL  $0x08, github·com∕segmentio∕asm∕cpu·X86+0(SB)
	JCS  avx2

generic:
	MOVB (DX), SI
	MOVB 1(DX), DI
	CMPB SI, DI
	JE   found
	ADDQ $0x01, DX
	CMPQ DX, BX
	JNE  generic

done:
	MOVQ CX, ret+24(FP)
	RET

found:
	SUBQ AX, DX
	MOVQ DX, ret+24(FP)
	RET

avx2:
	MOVQ BX, SI
	SUBQ $0x21, SI
	MOVQ $0x0000000000000000, DI

avx2_loop:
	VMOVDQU   (DX), Y0
	VMOVDQU   1(DX), Y1
	VPCMPEQB  Y0, Y1, Y1
	VPMOVMSKB Y1, DI
	TZCNTQ    DI, DI
	CMPQ      DI, $0x40
	JNE       avx2_found
	ADDQ      $0x20, DX
	CMPQ      DX, SI
	JBE       avx2_loop
	VZEROUPPER
	CMPQ      DX, BX
	JB        generic
	JMP       done

avx2_found:
	ADDQ DI, DX
	VZEROUPPER
	JMP  found

// func indexPair2(b []byte) int
// Requires: AVX, AVX2, BMI
TEXT ·indexPair2(SB), NOSPLIT, $0-32
	MOVQ b_base+0(FP), AX
	MOVQ b_len+8(FP), CX
	CMPQ CX, $0x02
	JBE  done
	MOVQ AX, DX
	MOVQ AX, BX
	ADDQ CX, BX
	SUBQ $0x02, BX
	CMPQ CX, $0x22
	JBE  generic
	BTL  $0x08, github·com∕segmentio∕asm∕cpu·X86+0(SB)
	JCS  avx2

generic:
	MOVW (DX), SI
	MOVW 2(DX), DI
	CMPW SI, DI
	JE   found
	ADDQ $0x02, DX
	CMPQ DX, BX
	JNE  generic

done:
	MOVQ CX, ret+24(FP)
	RET

found:
	SUBQ AX, DX
	MOVQ DX, ret+24(FP)
	RET

avx2:
	MOVQ BX, SI
	SUBQ $0x22, SI
	MOVQ $0x0000000000000000, DI

avx2_loop:
	VMOVDQU   (DX), Y0
	VMOVDQU   2(DX), Y1
	VPCMPEQW  Y0, Y1, Y1
	VPMOVMSKB Y1, DI
	TZCNTQ    DI, DI
	CMPQ      DI, $0x40
	JNE       avx2_found
	ADDQ      $0x20, DX
	CMPQ      DX, SI
	JBE       avx2_loop
	VZEROUPPER
	CMPQ      DX, BX
	JB        generic
	JMP       done

avx2_found:
	ADDQ DI, DX
	VZEROUPPER
	JMP  found

// func indexPair4(b []byte) int
// Requires: AVX, AVX2, BMI
TEXT ·indexPair4(SB), NOSPLIT, $0-32
	MOVQ b_base+0(FP), AX
	MOVQ b_len+8(FP), CX
	CMPQ CX, $0x04
	JBE  done
	MOVQ AX, DX
	MOVQ AX, BX
	ADDQ CX, BX
	SUBQ $0x04, BX
	CMPQ CX, $0x24
	JBE  generic
	BTL  $0x08, github·com∕segmentio∕asm∕cpu·X86+0(SB)
	JCS  avx2

generic:
	MOVL (DX), SI
	MOVL 4(DX), DI
	CMPL SI, DI
	JE   found
	ADDQ $0x04, DX
	CMPQ DX, BX
	JNE  generic

done:
	MOVQ CX, ret+24(FP)
	RET

found:
	SUBQ AX, DX
	MOVQ DX, ret+24(FP)
	RET

avx2:
	MOVQ BX, SI
	SUBQ $0x24, SI
	MOVQ $0x0000000000000000, DI

avx2_loop:
	VMOVDQU   (DX), Y0
	VMOVDQU   4(DX), Y1
	VPCMPEQD  Y0, Y1, Y1
	VPMOVMSKB Y1, DI
	TZCNTQ    DI, DI
	CMPQ      DI, $0x40
	JNE       avx2_found
	ADDQ      $0x20, DX
	CMPQ      DX, SI
	JBE       avx2_loop
	VZEROUPPER
	CMPQ      DX, BX
	JB        generic
	JMP       done

avx2_found:
	ADDQ DI, DX
	VZEROUPPER
	JMP  found

// func indexPair8(b []byte) int
// Requires: AVX, AVX2, BMI
TEXT ·indexPair8(SB), NOSPLIT, $0-32
	MOVQ b_base+0(FP), AX
	MOVQ b_len+8(FP), CX
	CMPQ CX, $0x08
	JBE  done
	MOVQ AX, DX
	MOVQ AX, BX
	ADDQ CX, BX
	SUBQ $0x08, BX
	CMPQ CX, $0x28
	JBE  generic
	BTL  $0x08, github·com∕segmentio∕asm∕cpu·X86+0(SB)
	JCS  avx2

generic:
	MOVQ (DX), SI
	MOVQ 8(DX), DI
	CMPQ SI, DI
	JE   found
	ADDQ $0x08, DX
	CMPQ DX, BX
	JNE  generic

done:
	MOVQ CX, ret+24(FP)
	RET

found:
	SUBQ AX, DX
	MOVQ DX, ret+24(FP)
	RET

avx2:
	MOVQ BX, SI
	SUBQ $0x28, SI
	MOVQ $0x0000000000000000, DI

avx2_loop:
	VMOVDQU   (DX), Y0
	VMOVDQU   8(DX), Y1
	VPCMPEQQ  Y0, Y1, Y1
	VPMOVMSKB Y1, DI
	TZCNTQ    DI, DI
	CMPQ      DI, $0x40
	JNE       avx2_found
	ADDQ      $0x20, DX
	CMPQ      DX, SI
	JBE       avx2_loop
	VZEROUPPER
	CMPQ      DX, BX
	JB        generic
	JMP       done

avx2_found:
	ADDQ DI, DX
	VZEROUPPER
	JMP  found

// func indexPair16(b []byte) int
// Requires: AVX, AVX2, SSE2, SSE4.1
TEXT ·indexPair16(SB), NOSPLIT, $0-32
	MOVQ b_base+0(FP), AX
	MOVQ b_len+8(FP), CX
	CMPQ CX, $0x10
	JBE  done
	MOVQ AX, DX
	MOVQ AX, BX
	ADDQ CX, BX
	SUBQ $0x10, BX
	CMPQ CX, $0x30
	JBE  generic
	BTL  $0x08, github·com∕segmentio∕asm∕cpu·X86+0(SB)
	JCS  avx2

generic:
	MOVOU    (DX), X0
	MOVOU    16(DX), X1
	PCMPEQQ  X0, X1
	PMOVMSKB X1, SI
	CMPL     SI, $0x0000ffff
	JE       found
	ADDQ     $0x10, DX
	CMPQ     DX, BX
	JNE      generic

done:
	MOVQ CX, ret+24(FP)
	RET

found:
	SUBQ AX, DX
	MOVQ DX, ret+24(FP)
	RET

avx2:
	MOVQ BX, SI
	SUBQ $0x30, SI
	MOVQ $0x0000000000000000, DI

avx2_loop:
	VMOVDQU   (DX), Y0
	VMOVDQU   16(DX), Y1
	VPCMPEQQ  Y0, Y1, Y1
	VPMOVMSKB Y1, DI
	MOVQ      DI, R8
	MOVQ      DI, R9
	SHRQ      $0x10, R8
	ANDQ      $0x0000ffff, R9
	MOVQ      $0x0000000000000000, DI
	CMPQ      R9, $0x0000ffff
	JE        avx2_found
	MOVQ      $0x0000000000000010, DI
	CMPQ      R8, $0x0000ffff
	JE        avx2_found
	ADDQ      $0x20, DX
	CMPQ      DX, SI
	JBE       avx2_loop
	VZEROUPPER
	CMPQ      DX, BX
	JB        generic
	JMP       done

avx2_found:
	ADDQ DI, DX
	VZEROUPPER
	JMP  found
