// Code generated by command: go run mask_asm.go -pkg mem -out ../mem/mask_amd64.s -stubs ../mem/mask_amd64.go. DO NOT EDIT.

package mem

// AVX optimized version for medium to large size inputs.
func Mask(dst []byte, src []byte) int
