// Code generated by command: go run decode_asm.go -pkg base64 -out ../base64/decode_amd64.s -stubs ../base64/decode_amd64.go. DO NOT EDIT.

package base64

func decodeAVX2(dst []byte, src []byte, lut [16]int8) (int, int)
