// Code generated by command: go run std_asm.go -pkg base64 -out ../base64/std_amd64.s -stubs ../base64/std_amd64.go. DO NOT EDIT.

package base64

func stdEncodeAVX2(dst []byte, src []byte) (int, int)
