// Code generated by command: go run copy_asm.go -pkg bloom -out ../bloom/copy_amd64.s -stubs ../bloom/copy_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func Copy(dst []byte, src []byte) int
// Requires: CMOV
TEXT ·Copy(SB), NOSPLIT, $0-56
	MOVQ    dst_base+0(FP), AX
	MOVQ    src_base+24(FP), CX
	MOVQ    dst_len+8(FP), DX
	MOVQ    src_len+32(FP), BX
	CMPQ    BX, DX
	CMOVQGT BX, DX
	MOVQ    DX, BX

cmp8:
	CMPQ BX, $0x08
	JB   cmp4
	MOVQ (CX), SI
	ORQ  SI, (AX)
	ADDQ $0x08, AX
	ADDQ $0x08, CX
	SUBQ $0x08, BX
	JMP  cmp8

cmp4:
	CMPQ BX, $0x04
	JB   cmp2
	MOVL (CX), SI
	ORL  SI, (AX)
	ADDQ $0x04, AX
	ADDQ $0x04, CX
	SUBQ $0x04, BX

cmp2:
	CMPQ BX, $0x02
	JB   cmp1
	MOVW (CX), SI
	ORW  SI, (AX)
	ADDQ $0x02, AX
	ADDQ $0x02, CX
	SUBQ $0x02, BX

cmp1:
	CMPQ BX, $0x01
	JB   done
	MOVB (CX), CL
	ORB  CL, (AX)

done:
	MOVQ DX, ret+48(FP)
	RET
