// Code generated by command: go run copy_asm.go -pkg bloom -out ../bloom/copy_amd64.s -stubs ../bloom/copy_amd64.go. DO NOT EDIT.

package bloom

// Copy copies the one-bits of src to dst, returning the number of bytes written.
func Copy(dst []byte, src []byte) int
