// Code generated by command: go run dedupe_asm.go -pkg sortedset -out ../sortedset/dedupe_amd64.s -stubs ../sortedset/dedupe_amd64.go. DO NOT EDIT.

package sortedset

func dedupe1(b []byte) int

func dedupe2(b []byte) int

func dedupe4(b []byte) int

func dedupe8(b []byte) int

func dedupe16(b []byte) int

func dedupe32(b []byte) int
