// Code generated by command: go run dedupe32_asm.go -pkg sortedset -out ../sortedset/dedupe32_amd64.s -stubs ../sortedset/dedupe32_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func dedupe32(b []byte) (pos int)
// Requires: AVX, AVX2
TEXT ·dedupe32(SB), NOSPLIT, $0-32
	MOVQ    b_base+0(FP), AX
	MOVQ    b_len+8(FP), CX
	MOVQ    AX, DX
	ADDQ    CX, DX
	VMOVUPS (AX), Y0
	ADDQ    $0x20, AX
	MOVQ    AX, CX

loop:
	CMPQ      AX, DX
	JE        done
	VMOVUPS   (AX), Y1
	ADDQ      $0x20, AX
	VPCMPEQB  Y0, Y1, Y2
	VPMOVMSKB Y2, BX
	CMPL      BX, $0xffffffff
	JE        loop
	VMOVUPS   Y1, (CX)
	ADDQ      $0x20, CX
	VMOVUPS   Y1, Y0
	JMP       loop

done:
	MOVQ b_base+0(FP), AX
	SUBQ AX, CX
	MOVQ CX, pos+24(FP)
	VZEROUPPER
	RET
