// Code generated by command: go run dedupe16_asm.go -pkg sortedset -out ../sortedset/dedupe16_amd64.s -stubs ../sortedset/dedupe16_amd64.go. DO NOT EDIT.

package sortedset

func dedupe16(b []byte) (pos int)
