// Code generated by command: go run dedupe_asm.go -pkg sortedset -out ../sortedset/dedupe_amd64.s -stubs ../sortedset/dedupe_amd64.go. DO NOT EDIT.

//go:build !purego

package sortedset

func dedupe1(dst []byte, src []byte) int

func dedupe2(dst []byte, src []byte) int

func dedupe4(dst []byte, src []byte) int

func dedupe8(dst []byte, src []byte) int

func dedupe16(dst []byte, src []byte) int

func dedupe32(dst []byte, src []byte) int
