// Code generated by command: go run intersect16_asm.go -pkg sortedset -out ../sortedset/intersect16_amd64.s -stubs ../sortedset/intersect16_amd64.go. DO NOT EDIT.

//go:build !purego

package sortedset

func intersect16(dst []byte, a []byte, b []byte) int
