// Code generated by command: go run union16_asm.go -pkg sortedset -out ../sortedset/union16_amd64.s -stubs ../sortedset/union16_amd64.go. DO NOT EDIT.

//go:build !purego

package sortedset

func union16(dst []byte, a []byte, b []byte) (i int, j int, k int)
