// Code generated by command: go run sort_asm.go -pkg qsort -out ../qsort/sort_amd64.s -stubs ../qsort/sort_amd64.go. DO NOT EDIT.

package qsort

func insertionsort128NoSwap(data []byte)

func distributeForward128(data *byte, scratch *byte, limit int, lo int, hi int, pivot int) int

func distributeBackward128(data *byte, scratch *byte, limit int, lo int, hi int, pivot int) int

func insertionsort256NoSwap(data []byte)

func distributeForward256(data *byte, scratch *byte, limit int, lo int, hi int, pivot int) int

func distributeBackward256(data *byte, scratch *byte, limit int, lo int, hi int, pivot int) int
