// Code generated by command: go run sort_asm.go -pkg qsort -out ../qsort/sort_amd64.s -stubs ../qsort/sort_amd64.go. DO NOT EDIT.

//go:build !purego

package qsort

//go:noescape
func distributeForward64(data []uint64, scratch []uint64, limit int, lo int, hi int) int

//go:noescape
func distributeBackward64(data []uint64, scratch []uint64, limit int, lo int, hi int) int

//go:noescape
func insertionsort128NoSwap(data []struct {
	hi uint64
	lo uint64
}, base int, swap func(int, int))

//go:noescape
func distributeForward128(data []struct {
	hi uint64
	lo uint64
}, scratch []struct {
	hi uint64
	lo uint64
}, limit int, lo int, hi int) int

//go:noescape
func distributeBackward128(data []struct {
	hi uint64
	lo uint64
}, scratch []struct {
	hi uint64
	lo uint64
}, limit int, lo int, hi int) int

//go:noescape
func insertionsort256NoSwap(data []struct {
	a uint64
	b uint64
	c uint64
	d uint64
}, base int, swap func(int, int))

//go:noescape
func distributeForward256(data []struct {
	a uint64
	b uint64
	c uint64
	d uint64
}, scratch []struct {
	a uint64
	b uint64
	c uint64
	d uint64
}, limit int, lo int, hi int) int

//go:noescape
func distributeBackward256(data []struct {
	a uint64
	b uint64
	c uint64
	d uint64
}, scratch []struct {
	a uint64
	b uint64
	c uint64
	d uint64
}, limit int, lo int, hi int) int
