// Code generated by command: go run keyset_asm.go -pkg keyset -out ../keyset/keyset_amd64.s -stubs ../keyset/keyset_amd64.go. DO NOT EDIT.

// +build !purego

#include "textflag.h"

// func search16(buffer *byte, lengths []uint32, key []byte) int
// Requires: AVX
TEXT ·search16(SB), NOSPLIT, $0-64
	MOVQ    key_base+32(FP), AX
	MOVQ    key_len+40(FP), CX
	CMPQ    CX, $0x10
	JA      notfound
	MOVQ    buffer+0(FP), DX
	MOVQ    lengths_base+8(FP), BX
	MOVQ    lengths_len+16(FP), SI
	VMOVUPS (AX), X0
	MOVQ    $0x00000001, AX
	SHLQ    CL, AX
	DECQ    AX
	XORQ    DI, DI
	XORQ    R8, R8

loop:
	CMPQ      R8, SI
	JE        done
	CMPL      CX, (BX)(R8*4)
	JNE       next
	VMOVUPS   (DX), X1
	VPCMPEQB  X1, X0, X1
	VPMOVMSKB X1, DI
	ANDQ      AX, DI
	CMPQ      AX, DI
	JE        done

next:
	INCQ R8
	ADDQ $0x10, DX
	JMP  loop

done:
	MOVQ R8, ret+56(FP)
	RET

notfound:
	MOVQ SI, ret+56(FP)
	RET
