// Code generated by command: go run keyset_asm.go -pkg keyset -out ../keyset/keyset_amd64.s -stubs ../keyset/keyset_amd64.go. DO NOT EDIT.

//go:build !purego
// +build !purego

package keyset

func search16(buffer *byte, lengths []uint32, key []byte) int
