// Code generated by command: go run valid_asm.go -pkg utf8 -out ../utf8/valid_amd64.s -stubs ../utf8/valid_amd64.go. DO NOT EDIT.

//go:build !purego
// +build !purego

package utf8

// Valid reports whether p consists entirely of valid UTF-8-encoded runes.
func Valid(p []byte) bool
