// Code generated by command: go run valid_asm.go -pkg utf8 -out ../utf8/valid_amd64.s -stubs ../utf8/valid_amd64.go. DO NOT EDIT.

//go:build !purego

package utf8

// Optimized version of Validate for inputs of more than 32B.
func validateAvx(p []byte) byte
