// Code generated by command: go run valid_asm.go -pkg ascii -out ../ascii/valid_amd64.s -stubs ../ascii/valid_amd64.go. DO NOT EDIT.

//go:build !purego
// +build !purego

package ascii

// validString returns true if s contains only ASCII characters.
func validString(s string, abi uint64) bool
